//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_users
    {
        public int pk_ID { get; set; }
        public int fk_ID_product { get; set; }
        public int fk_ID_user { get; set; }
        public int Количество { get; set; }
        public decimal Сумма { get; set; }
    
        public virtual products products { get; set; }
        public virtual users users { get; set; }
    }
}
